### ISSUE TITLE
aliasPackage.go:195: cast.Assign undefined (type *ast.TypeSpec has no field or method Assign)

### ISSUE THREAD

**Issue by nim-nim** [marstr/goalias#4]
I seem to have little luck with the unit tests of this package…

#+ go test -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro  '\'''
# github.com/marstr/goalias/model
#./aliasPackage.go:195: cast.Assign undefined (type *ast.TypeSpec has no field or method Assign)

**Comment by marstr** [comment]
Howdy, sorry I haven't been monitoring issues on this repository!

The error that you mention specifically comes up when you are not executing with at least go1.9. Please upgrade and let me know if you still run into this problem.
